[[gismo]]
arch = "aarch64"
git-tree-sha1 = "5f4a74d0a2ee921ce40d7d636feb5882ccfbe48f"
os = "macos"

    [[gismo.download]]
    sha256 = "17df3187269edd1aa751b12f5f43a5aeceb12a92616c09874c669dfa207fca2d"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.aarch64-apple-darwin.tar.gz"
[[gismo]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ffa01cff9216ad0fb3af7f8d6fe6e72dcc846d2c"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "e5fa4be7cb5fe5ba270781f330452b6ea288733c55d75d3071a4ff67422a88fa"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[gismo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9be3fdb51c39aeb85669ed20129e703c558e823"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "1d589cf1ed86f4583d631e69b0b83352d6d73f0733f6c3bbfb3c8ffcf50f214d"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[gismo]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "838818917e36d16d7f0ce82a8a118958a812835f"
libc = "musl"
os = "linux"

    [[gismo.download]]
    sha256 = "b00cb225fca240a8039c586e657fe5d148ccd86d9972038a2c58379156286e59"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[gismo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78ca1bc577c88d29d4dfc0fedea18269b862035f"
libc = "musl"
os = "linux"

    [[gismo.download]]
    sha256 = "58e12434768bfce8c00b10b6c669f2bdb163da129e0137cd10bc08fbdf250281"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[gismo]]
arch = "aarch64"
git-tree-sha1 = "5fa25db6e67add5e2d02fcf3527a754bb17cbe81"
os = "freebsd"

    [[gismo.download]]
    sha256 = "0571478734a2bdcc26260b92ca985fe0d6d959bbc168b2e19ca47ada06d981c7"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.aarch64-unknown-freebsd.tar.gz"
[[gismo]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42e2dc58fb14841e3b102d40575efa4ad01e8059"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "7d006a18d05e8b671e4644831d8483dc2d0dc792dba2dae0681ea20d80668587"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[gismo]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "071c4c9e9213ffbd50129260af512b0874863e81"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "a68f0308564582b08fd74a5f50b9cc3ee176ad60fc89abc6ba10c579f71455c7"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[gismo]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7ba0f30b3090f63df997c9e4c25ee31c20a250f"
libc = "musl"
os = "linux"

    [[gismo.download]]
    sha256 = "e76ba2038d51cf110f09fa17c6aab3b08ecc52c41b4698e753263036f7c1fcaf"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[gismo]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "359f9ca23fb35fc049ca2479a3a169b4e88fbaaf"
libc = "musl"
os = "linux"

    [[gismo.download]]
    sha256 = "71dd9061b07f2d5428b67f5496ebba10f5ffbad216f55852aa52ef1cdd1da1f3"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[gismo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39b4c671a2f2e0609dad09de4fa5b3da95e9db23"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "a2d74e1190954cc757ba9b972a798c09001467645be925bf748c6f47ad4fea93"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[gismo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d9bff72ca93b66f76477c4ed8113cabccdf2623"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "39ba671af5df76c1b111559226fffd7e8e99694057c93e8411d6b6121bab4234"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[gismo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f5f639a36a00551a0912899d751506b480f0f70"
libc = "musl"
os = "linux"

    [[gismo.download]]
    sha256 = "42f0c09a3dfe3c7ecfaaa01898d177bca0a95866c02cb2f56268a4efc8170986"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[gismo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c0d670feea5a097be733531b2cb51e1cc34309a"
libc = "musl"
os = "linux"

    [[gismo.download]]
    sha256 = "fa97b3925630ebe8a9e33d2707d44870707db4857942b3066b736031ef933df3"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[gismo]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32fd6771b956a0316b6a829be95c93c9cbab9878"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "017f43d45281852329c628fd8958949cbdc4e7c8b5cb8468a177058dd1f5cc2c"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.i686-linux-gnu-cxx03.tar.gz"
[[gismo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fe1c6f54a2347d80455a4c7360c349525034052"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "012e1684c0333f256246816d9a223c9f43b2e49aff91aba14c624a2c7110ab5b"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.i686-linux-gnu-cxx11.tar.gz"
[[gismo]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b818beb44bc4add32f8f7f9785ee797baaccefb1"
libc = "musl"
os = "linux"

    [[gismo.download]]
    sha256 = "69f10c14022f480786322dc3ff5cc689918cb7acacedc0bca3ac46cc42d07243"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.i686-linux-musl-cxx03.tar.gz"
[[gismo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87f30ad6213652f96f0804594a32a7a9be445062"
libc = "musl"
os = "linux"

    [[gismo.download]]
    sha256 = "30a7c6456f8f814a1f8c21942924d9afbedc8821427826c75a92b5df49630d6a"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.i686-linux-musl-cxx11.tar.gz"
[[gismo]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e48f4b51afe58ec3fde679c81a31426fface4ba"
os = "windows"

    [[gismo.download]]
    sha256 = "cf85ebf24bcd1aa4aed46b3798ae9f09857cdaa206145f086c3a80f7b96fa077"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[gismo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2c435c0d232b48a527b5e293ff0751d77f4159a"
os = "windows"

    [[gismo.download]]
    sha256 = "550a110bfa0a74fbfdf1a5a2e0443aae5963b51976576040e88317d0498d2afb"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[gismo]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "afafc15f6398501222aebee4b8d850c22e3a26b2"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "45378c9db4b82155bda1eff86f118c136f21161377f29e1ec6c1412352c46d7c"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[gismo]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ee19b4508badb240bde52286be8af3fdfd9e753"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "1ec44a3e02214be4a9018acb4fd02aca987ec71941d2787b7497bd8e1d0320ee"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[gismo]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e51ccf3d74fc7e2ba9f247df343c5cd49adcf2a0"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "85b46341be8b7e16558b25eacaabc9a05658303170572989fc10ad1528a60379"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.riscv64-linux-gnu-cxx03.tar.gz"
[[gismo]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ec46a1e3a16f71cd7475157dc9459cbd2a017bd"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "59040e33b347530a28ce86f9030417e8df2732c764d9e02c05e8aacde8ebf8a1"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.riscv64-linux-gnu-cxx11.tar.gz"
[[gismo]]
arch = "x86_64"
git-tree-sha1 = "2d217a87fe7afd2fabfcee6a511f84201900bc68"
os = "macos"

    [[gismo.download]]
    sha256 = "f8ca28a18377903e6784c7a461efe12db01a5b670f9a1cc476375f7228618737"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.x86_64-apple-darwin.tar.gz"
[[gismo]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e86efaa8f1a4c89313da03bdb02634aafb3d4ffe"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "6f00463e494ae3bd4bfae48af1fdf58d30d42058fcc5ea136777a39d9b974ef5"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[gismo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4827df533be4173068fab056ca2c8798be5db4a1"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "29c2592ab8829e6aef8d7f1e8da4209654721d56e9940c53f9804dbcd85de0a6"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[gismo]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7c0b28dfc2c17d3f61fd1ddc7e74b02c5205ed9"
libc = "musl"
os = "linux"

    [[gismo.download]]
    sha256 = "6a5ca5f8aff1a8e657968172f0f83ff17e51654f5123f8443f109c5bdd36b2a0"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[gismo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4805c5502090f3f7a2657e0ed677fcc9b25d3bab"
libc = "musl"
os = "linux"

    [[gismo.download]]
    sha256 = "638f3e91f15634122d6fc1390d8ecb5721f216dd882fb343340fb6df4711fa84"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[gismo]]
arch = "x86_64"
git-tree-sha1 = "372c328cfd60bc153144dc134cdd555fcea71c62"
os = "freebsd"

    [[gismo.download]]
    sha256 = "cc9040da1150777d58d531f0ff296ead58956567ce5865b6a221ff8b02337be9"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.x86_64-unknown-freebsd.tar.gz"
[[gismo]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca7a02abc2fd0572f61b2258c3502e0f995fcd64"
os = "windows"

    [[gismo.download]]
    sha256 = "de95bf02337c034712f30848247c89c2496f6209cdf4fc00c30d09bbb517c232"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[gismo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "289f50b0c647fa2ef13fbca352d790dde0083fdd"
os = "windows"

    [[gismo.download]]
    sha256 = "f95e733c7d11006f4b6be2753c92da1ded28e3a848a65f782295e63d7ff5ea77"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v25.1.0+0/gismo.v25.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
