[[gismo]]
arch = "aarch64"
git-tree-sha1 = "e502d11141bcd32dc56a0f1325738698276e907b"
os = "macos"

    [[gismo.download]]
    sha256 = "fd43b6cc03984e35ab962c288fc407550896ebfb70daea2135d02d55f6437a4e"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.aarch64-apple-darwin.tar.gz"
[[gismo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c63109d8518e55ae7ee35d3c3c112be5b3859ae7"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "5f20bd18eabbf0283335063f8b0062d99ff2acb2e7e1a6948b185504564b9976"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.aarch64-linux-gnu-cxx11.tar.gz"
[[gismo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7ce0d2d10778c5c62108b65153da2cc37030f37"
libc = "musl"
os = "linux"

    [[gismo.download]]
    sha256 = "218c970eb728e66ece2a307ad221c0d8d4d2351e23bd6a5db7ea900b84436c4b"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.aarch64-linux-musl-cxx11.tar.gz"
[[gismo]]
arch = "aarch64"
git-tree-sha1 = "d8b07ca40ea6895e070d3fd680074485b1e2fc60"
os = "freebsd"

    [[gismo.download]]
    sha256 = "945d64d5bae9e15acec5da8d04f083065364efd1248faaa4efafaf5c2019e384"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.aarch64-unknown-freebsd.tar.gz"
[[gismo]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08f47aea2c42da97057671d918f61e5134594830"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "a7e84da69579067b07981fae7fcf35e41c82d97a44608469024f95006f7f56a5"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[gismo]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c33ec0e0bf5b17030f72d35ae4cfe39569e3d1e9"
libc = "musl"
os = "linux"

    [[gismo.download]]
    sha256 = "aec743c6bdf52c7c178001a83d43deb20189228ac3ff32c866cfffd4df8e0434"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[gismo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "536e4ddccfaa0136c2cf2ca832a19c182e326ed1"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "ac97db5d52ef095d7148d81341099f4c575185141ccc8b745dfb18132259f297"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[gismo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc9ec5458051fdea2190d217c61f259e76275ffa"
libc = "musl"
os = "linux"

    [[gismo.download]]
    sha256 = "05fc88c0e991027ae7355cc6f3313e6ee6b655d2ac8bbb98258e1304ed162bc1"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[gismo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40a8256a943ee91a3f38335fcfe55ccc6ed2afe4"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "5a7214a8f9929f8b04265ea8f21e084dfc54dbd35f3673f304db3e330ecfb5ac"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.i686-linux-gnu-cxx11.tar.gz"
[[gismo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96c844f65b8e745aba9fd25cba495abc2de96b74"
libc = "musl"
os = "linux"

    [[gismo.download]]
    sha256 = "350543f5d1258bdc00836093e43dd5deebaee08dd6ff4189b8504332a1de81f8"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.i686-linux-musl-cxx11.tar.gz"
[[gismo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62ca7483437cfb298ed9aaf8c7bbb0d0d50eeb1e"
os = "windows"

    [[gismo.download]]
    sha256 = "971113174615c563715bc245464ffffcbbec3d7efa93e721df3422bbf6479521"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.i686-w64-mingw32-cxx11.tar.gz"
[[gismo]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18c72b5763dfd4a04c1014c72051378854ede17a"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "de6f02829839d8b4620c22c27f91c0ad7087cef4c74b3f07812d60170ff1c01d"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[gismo]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c6378049a4ea15b4d4e498d34d7d9e6b7311b9b"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "9840933248d4094ee9fa32f9faf4f78f0590a604880efc29fda22e33512281b9"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.riscv64-linux-gnu-cxx11.tar.gz"
[[gismo]]
arch = "x86_64"
git-tree-sha1 = "312fc0bc6165221d4fd7f96281b5375d712fb108"
os = "macos"

    [[gismo.download]]
    sha256 = "a3bd2111fb9074ae1e1485ce99592a47ba5e96e60ea19e60fc4c0c14664dd42a"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.x86_64-apple-darwin.tar.gz"
[[gismo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7aacc530903a404923a41257d8febef13a85699b"
libc = "glibc"
os = "linux"

    [[gismo.download]]
    sha256 = "bd7e0e38739d93ba2bfcaecd7a32657a18d7a4b3c63ba5b178cd1affcb1edb32"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.x86_64-linux-gnu-cxx11.tar.gz"
[[gismo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23d9b963fd9aa16f67b3c8cab4f1fb6a7f772bed"
libc = "musl"
os = "linux"

    [[gismo.download]]
    sha256 = "a82a2cf4ee4876097dba9aa853f9943e64f798ec1f3bb9d23c0e96bfb227a3ae"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.x86_64-linux-musl-cxx11.tar.gz"
[[gismo]]
arch = "x86_64"
git-tree-sha1 = "d82f659bf59165497927110fa99521ba17808c2d"
os = "freebsd"

    [[gismo.download]]
    sha256 = "d62898cff49ca643ce08134c837fec6ea2def29e11fe449682535f21fb55116d"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.x86_64-unknown-freebsd.tar.gz"
[[gismo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e6577291df147708b3f10a91fcdb80db281c65d"
os = "windows"

    [[gismo.download]]
    sha256 = "d1a4fe549b094e767f9b90aca4c225cd8067bc964813813f551bb9759bac49eb"
    url = "https://github.com/JuliaBinaryWrappers/gismo_jll.jl/releases/download/gismo-v26.9.0+0/gismo.v26.9.0.x86_64-w64-mingw32-cxx11.tar.gz"
