# Autogenerated wrapper script for gismo_jll for aarch64-unknown-freebsd
export libgismo

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("gismo")
JLLWrappers.@declare_library_product(libgismo, "libgismo.so.25")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libgismo,
        "lib/libgismo.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
